# Generated by Django 3.0.3 on 2020-02-06 13:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20200206_1256'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('author', 'content_type', 'object_id')},
        ),
    ]
